name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install inner-lens
        2. Add widget to component
        3. Click submit button
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happens...
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Package/Entry Point
      description: Which package or entry point are you using?
      options:
        - inner-lens (core)
        - inner-lens/react
        - inner-lens/vue
        - inner-lens/vanilla
        - inner-lens/server
        - CLI (npx inner-lens)
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Which frontend framework are you using?
      options:
        - React
        - Next.js (App Router)
        - Next.js (Pages Router)
        - Vue 3
        - Nuxt 3
        - Svelte
        - SvelteKit
        - Astro
        - Vanilla JS
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: inner-lens Version
      description: What version of inner-lens are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "20.10.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs or stack traces.
      render: shell

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample to reproduce the issue.
      render: typescript

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
