name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out this template to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: I would like inner-lens to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried...

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of inner-lens does this feature affect?
      options:
        - Widget (UI/UX)
        - Server Handlers
        - CLI
        - Session Replay
        - AI Analysis
        - Security/Masking
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking my adoption of inner-lens
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Example API/Usage
      description: If you have ideas on how the API should look, share them here.
      render: typescript
      placeholder: |
        // Example of how you'd like to use the feature
        <InnerLensWidget
          newFeature={true}
        />

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
